"""empty message

Revision ID: 32022a75076c
Revises: a5fde5eb563e
Create Date: 2017-04-24 12:32:56.495141

"""

# revision identifiers, used by Alembic.
revision = '32022a75076c'
down_revision = 'a5fde5eb563e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbs', sa.Column('user_management_view', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbs', 'user_management_view')
    # ### end Alembic commands ###
