"""empty message

Revision ID: 37592243fca3
Revises: 0aa1a3cd3e97
Create Date: 2017-05-22 15:42:07.589629

"""

# revision identifiers, used by Alembic.
revision = '37592243fca3'
down_revision = '0aa1a3cd3e97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbs', sa.Column('database_group', sa.String(length=1000), nullable=True))
    op.add_column('dbs', sa.Column('database_type', sa.String(length=1000), nullable=True))
    op.add_column('dbs', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbs', 'hidden')
    op.drop_column('dbs', 'database_type')
    op.drop_column('dbs', 'database_group')
    # ### end Alembic commands ###
