"""empty message

Revision ID: 3b861c4f0f44
Revises: 8c1f86b512f5
Create Date: 2017-05-31 11:11:47.896308

"""

# revision identifiers, used by Alembic.
revision = '3b861c4f0f44'
down_revision = '8c1f86b512f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_columns', sa.Column('is_hex', sa.Boolean(), nullable=True))
    op.drop_column('table_columns', 'encoded_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_columns', sa.Column('encoded_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('table_columns', 'is_hex')
    # ### end Alembic commands ###
