"""empty message

Revision ID: 633fd1b5a7ce
Revises: e1baae175dfa
Create Date: 2017-04-26 18:01:39.513998

"""

# revision identifiers, used by Alembic.
revision = '633fd1b5a7ce'
down_revision = 'e1baae175dfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('dbs', sa.Column('allow_hdfs_table', sa.Boolean(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('dbs', 'allow_hdfs_table')
    pass
    # ### end Alembic commands ###
