"""Add Coverage and Function to User Table

Revision ID: 6c6a820f1c94
Revises: 0a25c183d912
Create Date: 2018-03-13 02:14:11.132328

"""

# revision identifiers, used by Alembic.
revision = '6c6a820f1c94'
down_revision = '0a25c183d912'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_coverage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('ab_function',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('ab_permission_view_coverage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('permission_view_id', sa.Integer(), nullable=True),
        sa.Column('coverage_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['coverage_id'], ['ab_coverage.id'], ),
        sa.ForeignKeyConstraint(['permission_view_id'], ['ab_permission_view.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('permission_view_id', 'coverage_id')
    )
    op.create_table('ab_permission_view_function',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('permission_view_id', sa.Integer(), nullable=True),
        sa.Column('function_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['function_id'], ['ab_function.id'], ),
        sa.ForeignKeyConstraint(['permission_view_id'], ['ab_permission_view.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('permission_view_id', 'function_id')
    )
    op.add_column('ab_user', sa.Column('coverage_id', sa.Integer(), nullable=True))
    op.add_column('ab_user', sa.Column('function_id', sa.Integer(), nullable=True))
    op.create_foreign_key('abc', 'ab_user', 'ab_coverage', ['coverage_id'], ['id'])
    op.create_foreign_key('abf', 'ab_user', 'ab_function', ['function_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('abf', 'ab_user', type_='foreignkey')
    op.drop_constraint('abc', 'ab_user', type_='foreignkey')
    op.drop_column('ab_user', 'function_id')
    op.drop_column('ab_user', 'coverage_id')
    op.drop_table('ab_permission_view_function')
    op.drop_table('ab_permission_view_coverage')
    op.drop_table('ab_function')
    op.drop_table('ab_coverage')
    # ### end Alembic commands ###
