"""empty message

Revision ID: 8c1f86b512f5
Revises: 37592243fca3
Create Date: 2017-05-30 18:29:12.553558

"""

# revision identifiers, used by Alembic.
revision = '8c1f86b512f5'
down_revision = '37592243fca3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_columns', sa.Column('encoded_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_columns', 'encoded_type')
    # ### end Alembic commands ###
