"""empty message

Revision ID: a5fde5eb563e
Revises: c2f1335d8d5e
Create Date: 2017-04-20 11:13:17.909067

"""

# revision identifiers, used by Alembic.
revision = 'a5fde5eb563e'
down_revision = 'c2f1335d8d5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('parquet_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'parquet_path')
    # ### end Alembic commands ###
