"""empty message

Revision ID: c2f1335d8d5e
Revises: db527d8c4c78
Create Date: 2017-04-20 10:57:53.997406

"""

# revision identifiers, used by Alembic.
revision = 'c2f1335d8d5e'
down_revision = 'db527d8c4c78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbs', sa.Column('allow_parquet_table', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbs', 'allow_parquet_table')
    # ### end Alembic commands ###
