"""empty message

Revision ID: f40b61083a53
Revises: 3b861c4f0f44
Create Date: 2017-06-17 17:36:31.061756

"""

# revision identifiers, used by Alembic.
revision = 'f40b61083a53'
down_revision = '3b861c4f0f44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], [u'dbs.id'], ),
    sa.ForeignKeyConstraint(['role_id'], [u'ab_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'dbs', sa.Column('allow_create_table', sa.Boolean(), nullable=True))
    op.add_column(u'dbs', sa.Column('allow_hdfs_table', sa.Boolean(), nullable=True))
    op.drop_column(u'dbs', 'allow_parquet_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dbs', sa.Column('allow_parquet_table', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column(u'dbs', 'allow_hdfs_table')
    op.drop_column(u'dbs', 'allow_create_table')
    op.drop_table('role_database')
    # ### end Alembic commands ###
